"'Category Configuration_AddCategory' As screen":
    Fill: =Color.White
    LoadingSpinnerColor: =App.Theme.Colors.Primary

    "'AddCategory Form' As form.PowerApps_CoreControls_Form":
        BorderColor: =App.Theme.Colors.Darker40
        DataSource: ='Category Configuration'
        DefaultMode: =FormMode.New
        Height: =196
        NumberOfColumns: =2
        UseFluentV9Cards: =true
        Width: =1296
        X: =12
        Y: =160
        ZIndex: =1

        Category_DataCard6 As typedDataCard.fluentV9TextualEditCard:
            BorderColor: =App.Theme.Colors.Darker40
            BorderStyle: =BorderStyle.Solid
            DataField: ="Title"
            Default: =ThisItem.Category
            DisplayMode: =Parent.DisplayMode
            DisplayName: =DataSourceInfo([@'Category Configuration'],DataSourceInfo.DisplayName,Category)
            Fill: =RGBA(0, 0, 0, 0)
            Height: =70
            MaxLength: =DataSourceInfo([@'Category Configuration'], DataSourceInfo.MaxLength, Category)
            Required: =false
            Update: =DataCardValue36.Value
            Width: =648
            X: =0
            Y: =0
            ZIndex: =2

            DataCardKey36 As Text:
                DisplayMode: =DisplayMode.Edit
                FontColor: =
                Height: =22
                Text: =Parent.DisplayName
                Weight: ='TextCanvas.Weight'.Semibold
                Width: =Parent.Width - 48
                Wrap: =false
                X: =24
                Y: =10
                ZIndex: =1

            "DataCardValue36 As 'Text input'":
                AccessibleLabel: =Parent.DisplayName
                BasePaletteColor: =
                DisplayMode: =Parent.DisplayMode
                FontColor: =
                Height: =32
                Mode: ="'TextInputCanvas.Mode'.TextInputModeSingleLine"
                Required: =Parent.Required
                ValidationState: =If(IsBlank(Parent.Error), "None", "Error")
                Value: =Parent.Default
                Width: =Parent.Width - 48
                X: =24
                Y: =DataCardKey36.Y + DataCardKey36.Height + 4
                ZIndex: =2

            ErrorMessage29 As Text:
                DisplayMode: =DisplayMode.Edit
                FontColor: =
                Height: =30
                Text: =Parent.Error
                Visible: =And(!IsBlank(Parent.Error), Parent.DisplayMode=DisplayMode.Edit)
                Width: =Parent.Width - 48
                Wrap: =true
                X: =24
                Y: =DataCardValue36.Y + DataCardValue36.Height
                ZIndex: =3

            StarVisible29 As Text:
                Align: ='TextCanvas.Align'.Center
                DisplayMode: =DisplayMode.Edit
                FontColor: =
                Height: =30
                Text: ="*"
                Visible: =And(Parent.Required, Parent.DisplayMode=DisplayMode.Edit)
                Width: =30
                X: =0
                Y: =DataCardKey36.Y
                ZIndex: =4

        "'Sub Category_DataCard4' As typedDataCard.fluentV9TextualEditCard":
            BorderColor: =App.Theme.Colors.Darker40
            BorderStyle: =BorderStyle.Solid
            DataField: ="SubCategory"
            Default: =ThisItem.'Sub Category'
            DisplayMode: =Parent.DisplayMode
            DisplayName: =DataSourceInfo([@'Category Configuration'],DataSourceInfo.DisplayName,'Sub Category')
            Fill: =RGBA(0, 0, 0, 0)
            Height: =70
            MaxLength: =DataSourceInfo([@'Category Configuration'], DataSourceInfo.MaxLength, 'Sub Category')
            Required: =false
            Update: =DataCardValue37.Value
            Width: =648
            X: =1
            Y: =0
            ZIndex: =2

            DataCardKey37 As Text:
                DisplayMode: =DisplayMode.Edit
                FontColor: =
                Height: =22
                Text: =Parent.DisplayName
                Weight: ='TextCanvas.Weight'.Semibold
                Width: =Parent.Width - 48
                Wrap: =false
                X: =24
                Y: =10
                ZIndex: =1

            "DataCardValue37 As 'Text input'":
                AccessibleLabel: =Parent.DisplayName
                BasePaletteColor: =
                DisplayMode: =Parent.DisplayMode
                FontColor: =
                Height: =32
                Mode: ="'TextInputCanvas.Mode'.TextInputModeSingleLine"
                Required: =Parent.Required
                ValidationState: =If(IsBlank(Parent.Error), "None", "Error")
                Value: =Parent.Default
                Width: =Parent.Width - 48
                X: =24
                Y: =DataCardKey37.Y + DataCardKey37.Height + 4
                ZIndex: =2

            ErrorMessage30 As Text:
                DisplayMode: =DisplayMode.Edit
                FontColor: =
                Height: =30
                Text: =Parent.Error
                Visible: =And(!IsBlank(Parent.Error), Parent.DisplayMode=DisplayMode.Edit)
                Width: =Parent.Width - 48
                Wrap: =true
                X: =24
                Y: =DataCardValue37.Y + DataCardValue37.Height
                ZIndex: =3

            StarVisible30 As Text:
                Align: ='TextCanvas.Align'.Center
                DisplayMode: =DisplayMode.Edit
                FontColor: =
                Height: =30
                Text: ="*"
                Visible: =And(Parent.Required, Parent.DisplayMode=DisplayMode.Edit)
                Width: =30
                X: =0
                Y: =DataCardKey37.Y
                ZIndex: =4

        "'Category Groups_DataCard2' As typedDataCard.fluentV9ComboBoxMultiSelectEditCard":
            BorderColor: =App.Theme.Colors.Darker40
            BorderStyle: =BorderStyle.Solid
            DataField: ="Category_x0020_Groups"
            Default: =ThisItem.'Category Groups'
            DisplayMode: =Parent.DisplayMode
            DisplayName: =DataSourceInfo([@'Category Configuration'],DataSourceInfo.DisplayName,'Category Groups')
            Fill: =RGBA(0, 0, 0, 0)
            Height: =70
            Required: =false
            Update: =DataCardValue38.SelectedItems
            Width: =648
            X: =0
            Y: =1
            ZIndex: =2

            DataCardKey38 As Text:
                DisplayMode: =DisplayMode.Edit
                FontColor: =
                Height: =22
                Text: =Parent.DisplayName
                Weight: ='TextCanvas.Weight'.Semibold
                Width: =Parent.Width - 48
                Wrap: =false
                X: =24
                Y: =10
                ZIndex: =1

            DataCardValue38 As Combobox.pcfdataset:
                AccessibleLabel: =If(Parent.Required, Substitute("{0}. Required.", "{0}", Parent.DisplayName), Parent.DisplayName)
                DefaultSelectedItems: =[Parent.Default]
                DisplayMode: =Parent.DisplayMode
                Height: =32
                Items: =Choices([@'Category Configuration'].'Category Groups')
                SelectMultiple: =true
                ValidationState: =If(IsBlank(Parent.Error), "None", "Error")
                Width: =Parent.Width - 48
                X: =24
                Y: =DataCardKey38.Y + DataCardKey38.Height + 4
                ZIndex: =2

            ErrorMessage31 As Text:
                DisplayMode: =DisplayMode.Edit
                FontColor: =
                Height: =30
                Text: =Parent.Error
                Visible: =And(!IsBlank(Parent.Error), Parent.DisplayMode=DisplayMode.Edit)
                Width: =Parent.Width - 48
                Wrap: =true
                X: =24
                Y: =DataCardValue38.Y + DataCardValue38.Height
                ZIndex: =3

            StarVisible31 As Text:
                Align: ='TextCanvas.Align'.Center
                DisplayMode: =DisplayMode.Edit
                FontColor: =
                Height: =20
                Text: ="*"
                Visible: =And(Parent.Required, Parent.DisplayMode=DisplayMode.Edit)
                Width: =30
                X: =0
                Y: =DataCardKey38.Y
                ZIndex: =4

        "'Sub Category Groups_DataCard2' As typedDataCard.fluentV9ComboBoxMultiSelectEditCard":
            BorderColor: =App.Theme.Colors.Darker40
            BorderStyle: =BorderStyle.Solid
            DataField: ="Sub_x0020_Category_x0020_Groups"
            Default: =ThisItem.'Sub Category Groups'
            DisplayMode: =Parent.DisplayMode
            DisplayName: =DataSourceInfo([@'Category Configuration'],DataSourceInfo.DisplayName,'Sub Category Groups')
            Fill: =RGBA(0, 0, 0, 0)
            Height: =70
            Required: =false
            Update: =DataCardValue39.SelectedItems
            Width: =648
            X: =1
            Y: =1
            ZIndex: =2

            DataCardKey39 As Text:
                DisplayMode: =DisplayMode.Edit
                FontColor: =
                Height: =22
                Text: =Parent.DisplayName
                Weight: ='TextCanvas.Weight'.Semibold
                Width: =Parent.Width - 48
                Wrap: =false
                X: =24
                Y: =10
                ZIndex: =1

            DataCardValue39 As Combobox.pcfdataset:
                AccessibleLabel: =If(Parent.Required, Substitute("{0}. Required.", "{0}", Parent.DisplayName), Parent.DisplayName)
                DefaultSelectedItems: =[Parent.Default]
                DisplayMode: =Parent.DisplayMode
                Height: =32
                Items: =Choices([@'Category Configuration'].'Sub Category Groups')
                SelectMultiple: =true
                ValidationState: =If(IsBlank(Parent.Error), "None", "Error")
                Width: =Parent.Width - 48
                X: =24
                Y: =DataCardKey39.Y + DataCardKey39.Height + 4
                ZIndex: =2

            ErrorMessage32 As Text:
                DisplayMode: =DisplayMode.Edit
                FontColor: =
                Height: =30
                Text: =Parent.Error
                Visible: =And(!IsBlank(Parent.Error), Parent.DisplayMode=DisplayMode.Edit)
                Width: =Parent.Width - 48
                Wrap: =true
                X: =24
                Y: =DataCardValue39.Y + DataCardValue39.Height
                ZIndex: =3

            StarVisible32 As Text:
                Align: ='TextCanvas.Align'.Center
                DisplayMode: =DisplayMode.Edit
                FontColor: =
                Height: =20
                Text: ="*"
                Visible: =And(Parent.Required, Parent.DisplayMode=DisplayMode.Edit)
                Width: =30
                X: =0
                Y: =DataCardKey39.Y
                ZIndex: =4

    "Header_11 As '13c5175f2551439889fd1161e1fcd63c'":
        DestinationScreen: ='Category Configuration_List'
        HeaderText: ="Category Configuration"
        ZIndex: =2

    SubmitButton_2 As Button:
        BasePaletteColor: =
        DisplayMode: =DisplayMode.Edit
        FontColor: =
        Height: =32
        OnSelect: |-
            =
                //else res
            SubmitForm('AddCategory Form');
            ResetForm('AddCategory Form');
            Notify(
                "Add Category successfully!",
                NotificationType.Success,
                3000
            );
            NewForm('AddCategory Form')
        Text: |
            ="Submit"
        Width: =96
        X: =64
        Y: =600
        ZIndex: =3

    ButtonCanvas3_2 As Button:
        Appearance: ='ButtonCanvas.Appearance'.Secondary
        BasePaletteColor: =
        DisplayMode: =DisplayMode.Edit
        FontColor: =
        Height: =32
        OnSelect: =Navigate('Request List', ScreenTransition.Cover);
        Text: ="Cancel"
        Visible: =true
        Width: =96
        X: =179
        Y: =600
        ZIndex: =4

